### ISSUE TITLE
Add some samples source code..

### ISSUE THREAD

**Issue by oscarbg** [nyorain/vpp#3]
Hi,
you expose some source code of simple usage of your library but not complete samples with source code..
Can add some working simple sample with source code in examples folder even a simple "hello world" render nothing would be nice!

**Comment by nyorain** [comment]
hey that's a good idea, the programs in the example folder are rather outdated and not that simple. Since I am currently reworking some parts of vpp this might take a while, but will definitely do it.

In the end such a triangle "hello world" example would look much like the default vulkan example but with much less uninteresting code like setting the structure sTypes, handling the buffers memory requirements and allocation or caring much about the rather complex device and swapchain creation.
